services:
  db:
    image: postgres:16
    container_name: skins_postgres
    environment:
      POSTGRES_USER: skins 
      POSTGRES_PASSWORD: skins
      POSTGRES_DB: skins 
    ports:
      - "5432:5432"
    volumes:
      - skins_pgdata:/var/lib/postgresql/data
      - ./spear-it-skins-backend/db:/docker-entrypoint-initdb.d

volumes:
  skins_pgdata:
